// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AggregateField(arg1:Array<api.Document>,arg2:string,arg3:string):Promise<number>;

export function ArrangeDocuments(arg1:Array<api.Document>,arg2:api.ArrangeOptions):Promise<api.ArrangeResult>;

export function GetUniqueValues(arg1:Array<api.Document>,arg2:string):Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;

export function IndexFile(arg1:string):Promise<void>;
