// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AggregateField(arg1, arg2, arg3) {
  return window['go']['main']['App']['AggregateField'](arg1, arg2, arg3);
}

export function ArrangeDocuments(arg1, arg2) {
  return window['go']['main']['App']['ArrangeDocuments'](arg1, arg2);
}

export function GetUniqueValues(arg1, arg2) {
  return window['go']['main']['App']['GetUniqueValues'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IndexFile(arg1) {
  return window['go']['main']['App']['IndexFile'](arg1);
}
